//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidentUtility.DomainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isLoginValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isLoginValid {
            get {
                return this.isLoginValidField;
            }
            set {
                if ((this.isLoginValidField.Equals(value) != true)) {
                    this.isLoginValidField = value;
                    this.RaisePropertyChanged("isLoginValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultType2", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResultType2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADSearchResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ADSearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isLoginValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isLoginValid {
            get {
                return this.isLoginValidField;
            }
            set {
                if ((this.isLoginValidField.Equals(value) != true)) {
                    this.isLoginValidField = value;
                    this.RaisePropertyChanged("isLoginValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserNameDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserNameDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isLoginNameValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string isLoginNameValid {
            get {
                return this.isLoginNameValidField;
            }
            set {
                if ((object.ReferenceEquals(this.isLoginNameValidField, value) != true)) {
                    this.isLoginNameValidField = value;
                    this.RaisePropertyChanged("isLoginNameValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DomainService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name strLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        ProvidentUtility.DomainService.AuthenticateUserResponse AuthenticateUser(ProvidentUtility.DomainService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserResponse> AuthenticateUserAsync(ProvidentUtility.DomainService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name strLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetails", ReplyAction="*")]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse AuthenticateUserWithDetails(ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse> AuthenticateUserWithDetailsAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name strInputName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetailsViaLFM", ReplyAction="*")]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse AuthenticateUserWithDetailsViaLFM(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetailsViaLFM", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse> AuthenticateUserWithDetailsViaLFMAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest request);
        
        // CODEGEN: Generating message contract since element name strLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetailsViaUsername", ReplyAction="*")]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse AuthenticateUserWithDetailsViaUsername(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWithDetailsViaUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse> AuthenticateUserWithDetailsViaUsernameAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisplayName", ReplyAction="*")]
        ProvidentUtility.DomainService.GetDisplayNameResponse GetDisplayName(ProvidentUtility.DomainService.GetDisplayNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisplayName", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetDisplayNameResponse> GetDisplayNameAsync(ProvidentUtility.DomainService.GetDisplayNameRequest request);
        
        // CODEGEN: Generating message contract since element name LoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserNameDetailsViaLoginName", ReplyAction="*")]
        ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse GetUserNameDetailsViaLoginName(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserNameDetailsViaLoginName", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse> GetUserNameDetailsViaLoginNameAsync(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest request);
        
        // CODEGEN: Generating message contract since element name strLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserNameExisting", ReplyAction="*")]
        ProvidentUtility.DomainService.isUserNameExistingResponse isUserNameExisting(ProvidentUtility.DomainService.isUserNameExistingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserNameExisting", ReplyAction="*")]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.isUserNameExistingResponse> isUserNameExistingAsync(ProvidentUtility.DomainService.isUserNameExistingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(ProvidentUtility.DomainService.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string strLoginName, string strPassword) {
            this.strLoginName = strLoginName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(ProvidentUtility.DomainService.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetails", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequestBody Body;
        
        public AuthenticateUserWithDetailsRequest() {
        }
        
        public AuthenticateUserWithDetailsRequest(ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticateUserWithDetailsRequestBody() {
        }
        
        public AuthenticateUserWithDetailsRequestBody(string strLoginName, string strPassword) {
            this.strLoginName = strLoginName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponseBody Body;
        
        public AuthenticateUserWithDetailsResponse() {
        }
        
        public AuthenticateUserWithDetailsResponse(ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProvidentUtility.DomainService.LoginResult AuthenticateUserWithDetailsResult;
        
        public AuthenticateUserWithDetailsResponseBody() {
        }
        
        public AuthenticateUserWithDetailsResponseBody(ProvidentUtility.DomainService.LoginResult AuthenticateUserWithDetailsResult) {
            this.AuthenticateUserWithDetailsResult = AuthenticateUserWithDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsViaLFMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetailsViaLFM", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequestBody Body;
        
        public AuthenticateUserWithDetailsViaLFMRequest() {
        }
        
        public AuthenticateUserWithDetailsViaLFMRequest(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsViaLFMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strInputName;
        
        public AuthenticateUserWithDetailsViaLFMRequestBody() {
        }
        
        public AuthenticateUserWithDetailsViaLFMRequestBody(string strInputName) {
            this.strInputName = strInputName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsViaLFMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetailsViaLFMResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponseBody Body;
        
        public AuthenticateUserWithDetailsViaLFMResponse() {
        }
        
        public AuthenticateUserWithDetailsViaLFMResponse(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsViaLFMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProvidentUtility.DomainService.LoginResultType2[] AuthenticateUserWithDetailsViaLFMResult;
        
        public AuthenticateUserWithDetailsViaLFMResponseBody() {
        }
        
        public AuthenticateUserWithDetailsViaLFMResponseBody(ProvidentUtility.DomainService.LoginResultType2[] AuthenticateUserWithDetailsViaLFMResult) {
            this.AuthenticateUserWithDetailsViaLFMResult = AuthenticateUserWithDetailsViaLFMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsViaUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetailsViaUsername", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequestBody Body;
        
        public AuthenticateUserWithDetailsViaUsernameRequest() {
        }
        
        public AuthenticateUserWithDetailsViaUsernameRequest(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsViaUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        public AuthenticateUserWithDetailsViaUsernameRequestBody() {
        }
        
        public AuthenticateUserWithDetailsViaUsernameRequestBody(string strLoginName) {
            this.strLoginName = strLoginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithDetailsViaUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithDetailsViaUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponseBody Body;
        
        public AuthenticateUserWithDetailsViaUsernameResponse() {
        }
        
        public AuthenticateUserWithDetailsViaUsernameResponse(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWithDetailsViaUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProvidentUtility.DomainService.ADSearchResult AuthenticateUserWithDetailsViaUsernameResult;
        
        public AuthenticateUserWithDetailsViaUsernameResponseBody() {
        }
        
        public AuthenticateUserWithDetailsViaUsernameResponseBody(ProvidentUtility.DomainService.ADSearchResult AuthenticateUserWithDetailsViaUsernameResult) {
            this.AuthenticateUserWithDetailsViaUsernameResult = AuthenticateUserWithDetailsViaUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDisplayNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDisplayName", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.GetDisplayNameRequestBody Body;
        
        public GetDisplayNameRequest() {
        }
        
        public GetDisplayNameRequest(ProvidentUtility.DomainService.GetDisplayNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDisplayNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        public GetDisplayNameRequestBody() {
        }
        
        public GetDisplayNameRequestBody(string Username) {
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDisplayNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDisplayNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.GetDisplayNameResponseBody Body;
        
        public GetDisplayNameResponse() {
        }
        
        public GetDisplayNameResponse(ProvidentUtility.DomainService.GetDisplayNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDisplayNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDisplayNameResult;
        
        public GetDisplayNameResponseBody() {
        }
        
        public GetDisplayNameResponseBody(string GetDisplayNameResult) {
            this.GetDisplayNameResult = GetDisplayNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameDetailsViaLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameDetailsViaLoginName", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequestBody Body;
        
        public GetUserNameDetailsViaLoginNameRequest() {
        }
        
        public GetUserNameDetailsViaLoginNameRequest(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameDetailsViaLoginNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginName;
        
        public GetUserNameDetailsViaLoginNameRequestBody() {
        }
        
        public GetUserNameDetailsViaLoginNameRequestBody(string LoginName) {
            this.LoginName = LoginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameDetailsViaLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameDetailsViaLoginNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponseBody Body;
        
        public GetUserNameDetailsViaLoginNameResponse() {
        }
        
        public GetUserNameDetailsViaLoginNameResponse(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameDetailsViaLoginNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProvidentUtility.DomainService.UserNameDetails GetUserNameDetailsViaLoginNameResult;
        
        public GetUserNameDetailsViaLoginNameResponseBody() {
        }
        
        public GetUserNameDetailsViaLoginNameResponseBody(ProvidentUtility.DomainService.UserNameDetails GetUserNameDetailsViaLoginNameResult) {
            this.GetUserNameDetailsViaLoginNameResult = GetUserNameDetailsViaLoginNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUserNameExistingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUserNameExisting", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.isUserNameExistingRequestBody Body;
        
        public isUserNameExistingRequest() {
        }
        
        public isUserNameExistingRequest(ProvidentUtility.DomainService.isUserNameExistingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUserNameExistingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        public isUserNameExistingRequestBody() {
        }
        
        public isUserNameExistingRequestBody(string strLoginName) {
            this.strLoginName = strLoginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUserNameExistingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUserNameExistingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProvidentUtility.DomainService.isUserNameExistingResponseBody Body;
        
        public isUserNameExistingResponse() {
        }
        
        public isUserNameExistingResponse(ProvidentUtility.DomainService.isUserNameExistingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUserNameExistingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isUserNameExistingResult;
        
        public isUserNameExistingResponseBody() {
        }
        
        public isUserNameExistingResponseBody(string isUserNameExistingResult) {
            this.isUserNameExistingResult = isUserNameExistingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ProvidentUtility.DomainService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ProvidentUtility.DomainService.ServiceSoap>, ProvidentUtility.DomainService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.AuthenticateUserResponse ProvidentUtility.DomainService.ServiceSoap.AuthenticateUser(ProvidentUtility.DomainService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(string strLoginName, string strPassword) {
            ProvidentUtility.DomainService.AuthenticateUserRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            ProvidentUtility.DomainService.AuthenticateUserResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserResponse> ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserAsync(ProvidentUtility.DomainService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserResponse> AuthenticateUserAsync(string strLoginName, string strPassword) {
            ProvidentUtility.DomainService.AuthenticateUserRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetails(ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest request) {
            return base.Channel.AuthenticateUserWithDetails(request);
        }
        
        public ProvidentUtility.DomainService.LoginResult AuthenticateUserWithDetails(string strLoginName, string strPassword) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetails(inValue);
            return retVal.Body.AuthenticateUserWithDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse> ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetailsAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest request) {
            return base.Channel.AuthenticateUserWithDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsResponse> AuthenticateUserWithDetailsAsync(string strLoginName, string strPassword) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetailsViaLFM(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest request) {
            return base.Channel.AuthenticateUserWithDetailsViaLFM(request);
        }
        
        public ProvidentUtility.DomainService.LoginResultType2[] AuthenticateUserWithDetailsViaLFM(string strInputName) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequestBody();
            inValue.Body.strInputName = strInputName;
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetailsViaLFM(inValue);
            return retVal.Body.AuthenticateUserWithDetailsViaLFMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse> ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetailsViaLFMAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest request) {
            return base.Channel.AuthenticateUserWithDetailsViaLFMAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMResponse> AuthenticateUserWithDetailsViaLFMAsync(string strInputName) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaLFMRequestBody();
            inValue.Body.strInputName = strInputName;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetailsViaLFMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetailsViaUsername(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest request) {
            return base.Channel.AuthenticateUserWithDetailsViaUsername(request);
        }
        
        public ProvidentUtility.DomainService.ADSearchResult AuthenticateUserWithDetailsViaUsername(string strLoginName) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequestBody();
            inValue.Body.strLoginName = strLoginName;
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetailsViaUsername(inValue);
            return retVal.Body.AuthenticateUserWithDetailsViaUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse> ProvidentUtility.DomainService.ServiceSoap.AuthenticateUserWithDetailsViaUsernameAsync(ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest request) {
            return base.Channel.AuthenticateUserWithDetailsViaUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameResponse> AuthenticateUserWithDetailsViaUsernameAsync(string strLoginName) {
            ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest inValue = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequest();
            inValue.Body = new ProvidentUtility.DomainService.AuthenticateUserWithDetailsViaUsernameRequestBody();
            inValue.Body.strLoginName = strLoginName;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).AuthenticateUserWithDetailsViaUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.GetDisplayNameResponse ProvidentUtility.DomainService.ServiceSoap.GetDisplayName(ProvidentUtility.DomainService.GetDisplayNameRequest request) {
            return base.Channel.GetDisplayName(request);
        }
        
        public string GetDisplayName(string Username) {
            ProvidentUtility.DomainService.GetDisplayNameRequest inValue = new ProvidentUtility.DomainService.GetDisplayNameRequest();
            inValue.Body = new ProvidentUtility.DomainService.GetDisplayNameRequestBody();
            inValue.Body.Username = Username;
            ProvidentUtility.DomainService.GetDisplayNameResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).GetDisplayName(inValue);
            return retVal.Body.GetDisplayNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetDisplayNameResponse> ProvidentUtility.DomainService.ServiceSoap.GetDisplayNameAsync(ProvidentUtility.DomainService.GetDisplayNameRequest request) {
            return base.Channel.GetDisplayNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetDisplayNameResponse> GetDisplayNameAsync(string Username) {
            ProvidentUtility.DomainService.GetDisplayNameRequest inValue = new ProvidentUtility.DomainService.GetDisplayNameRequest();
            inValue.Body = new ProvidentUtility.DomainService.GetDisplayNameRequestBody();
            inValue.Body.Username = Username;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).GetDisplayNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse ProvidentUtility.DomainService.ServiceSoap.GetUserNameDetailsViaLoginName(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest request) {
            return base.Channel.GetUserNameDetailsViaLoginName(request);
        }
        
        public ProvidentUtility.DomainService.UserNameDetails GetUserNameDetailsViaLoginName(string LoginName) {
            ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest inValue = new ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest();
            inValue.Body = new ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequestBody();
            inValue.Body.LoginName = LoginName;
            ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).GetUserNameDetailsViaLoginName(inValue);
            return retVal.Body.GetUserNameDetailsViaLoginNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse> ProvidentUtility.DomainService.ServiceSoap.GetUserNameDetailsViaLoginNameAsync(ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest request) {
            return base.Channel.GetUserNameDetailsViaLoginNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameResponse> GetUserNameDetailsViaLoginNameAsync(string LoginName) {
            ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest inValue = new ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequest();
            inValue.Body = new ProvidentUtility.DomainService.GetUserNameDetailsViaLoginNameRequestBody();
            inValue.Body.LoginName = LoginName;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).GetUserNameDetailsViaLoginNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProvidentUtility.DomainService.isUserNameExistingResponse ProvidentUtility.DomainService.ServiceSoap.isUserNameExisting(ProvidentUtility.DomainService.isUserNameExistingRequest request) {
            return base.Channel.isUserNameExisting(request);
        }
        
        public string isUserNameExisting(string strLoginName) {
            ProvidentUtility.DomainService.isUserNameExistingRequest inValue = new ProvidentUtility.DomainService.isUserNameExistingRequest();
            inValue.Body = new ProvidentUtility.DomainService.isUserNameExistingRequestBody();
            inValue.Body.strLoginName = strLoginName;
            ProvidentUtility.DomainService.isUserNameExistingResponse retVal = ((ProvidentUtility.DomainService.ServiceSoap)(this)).isUserNameExisting(inValue);
            return retVal.Body.isUserNameExistingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProvidentUtility.DomainService.isUserNameExistingResponse> ProvidentUtility.DomainService.ServiceSoap.isUserNameExistingAsync(ProvidentUtility.DomainService.isUserNameExistingRequest request) {
            return base.Channel.isUserNameExistingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProvidentUtility.DomainService.isUserNameExistingResponse> isUserNameExistingAsync(string strLoginName) {
            ProvidentUtility.DomainService.isUserNameExistingRequest inValue = new ProvidentUtility.DomainService.isUserNameExistingRequest();
            inValue.Body = new ProvidentUtility.DomainService.isUserNameExistingRequestBody();
            inValue.Body.strLoginName = strLoginName;
            return ((ProvidentUtility.DomainService.ServiceSoap)(this)).isUserNameExistingAsync(inValue);
        }
    }
}
